-- MySQL Script generated by MySQL Workbench
-- Sun Oct  3 00:12:34 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `user_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(258) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`post` (
  `post_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(258) NULL,
  `content` MEDIUMTEXT NULL,
  `author` BIGINT NOT NULL,
  PRIMARY KEY (`post_id`),
  INDEX `fk_post_user_idx` (`author` ASC) VISIBLE,
  CONSTRAINT `fk_post_user`
    FOREIGN KEY (`author`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comment` (
  `comment_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `comment` TEXT NOT NULL,
  `author` BIGINT UNSIGNED NOT NULL,
  `commented_on` BIGINT UNSIGNED NOT NULL,
  `public` TINYINT NULL DEFAULT 1,
  `anonymous` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`comment_id`),
  INDEX `fk_comment_user1_idx` (`author` ASC) VISIBLE,
  UNIQUE INDEX `comment_id_UNIQUE` (`comment_id` ASC) VISIBLE,
  INDEX `fk_comment_post1_idx` (`commented_on` ASC) VISIBLE,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`author`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_post1`
    FOREIGN KEY (`commented_on`)
    REFERENCES `mydb`.`post` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`commented_hierarchy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`commented_hierarchy` (
  `comment_id` BIGINT UNSIGNED NOT NULL,
  `immediate_parent` BIGINT UNSIGNED NOT NULL COMMENT 'Comment Id for the comment on which this comment is posted',
  `super_parent` BIGINT UNSIGNED NOT NULL COMMENT 'Comment Id for the First comment for this comment (Root of the comment)',
  INDEX `fk_commented_on_comment1_idx` (`comment_id` ASC) VISIBLE,
  PRIMARY KEY (`comment_id`),
  UNIQUE INDEX `comment_id_UNIQUE` (`comment_id` ASC) VISIBLE,
  INDEX `fk_commented_on_comment2_idx` (`immediate_parent` ASC) VISIBLE,
  INDEX `fk_commented_on_comment3_idx` (`super_parent` ASC) VISIBLE,
  CONSTRAINT `fk_commented_on_comment1`
    FOREIGN KEY (`comment_id`)
    REFERENCES `mydb`.`comment` (`comment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commented_on_comment2`
    FOREIGN KEY (`immediate_parent`)
    REFERENCES `mydb`.`comment` (`comment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commented_on_comment3`
    FOREIGN KEY (`super_parent`)
    REFERENCES `mydb`.`comment` (`comment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`like` (
  `like_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `on_post` BIGINT UNSIGNED NULL,
  `on_comment` BIGINT UNSIGNED NULL,
  `liked_by` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`like_id`),
  INDEX `fk_like_post1_idx` (`on_post` ASC) VISIBLE,
  INDEX `fk_like_comment1_idx` (`on_comment` ASC) VISIBLE,
  INDEX `fk_like_user1_idx` (`liked_by` ASC) VISIBLE,
  CONSTRAINT `fk_like_post1`
    FOREIGN KEY (`on_post`)
    REFERENCES `mydb`.`post` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_like_comment1`
    FOREIGN KEY (`on_comment`)
    REFERENCES `mydb`.`comment` (`comment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_like_user1`
    FOREIGN KEY (`liked_by`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`suggestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`suggestion` (
  `suggestion_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `comment` BIGINT UNSIGNED NOT NULL,
  `status` VARCHAR(66) NOT NULL COMMENT 'Have an entry if the comment is a suggestion',
  PRIMARY KEY (`suggestion_id`),
  INDEX `fk_suggestion_comment1_idx` (`comment` ASC) VISIBLE,
  CONSTRAINT `fk_suggestion_comment1`
    FOREIGN KEY (`comment`)
    REFERENCES `mydb`.`comment` (`comment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`review` (
  `review_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `post` BIGINT UNSIGNED NOT NULL,
  `reviewcol` VARCHAR(66) NULL,
  `success` TINYINT NOT NULL DEFAULT 0 COMMENT 'Is successfully reviewd or not ?',
  `status` VARCHAR(66) NOT NULL,
  `related_comment` BIGINT UNSIGNED NOT NULL COMMENT 'Review for the Post requested to publicly publsh the post',
  PRIMARY KEY (`review_id`),
  INDEX `fk_review_post1_idx` (`post` ASC) VISIBLE,
  INDEX `fk_review_comment1_idx` (`related_comment` ASC) VISIBLE,
  CONSTRAINT `fk_review_post1`
    FOREIGN KEY (`post`)
    REFERENCES `mydb`.`post` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_comment1`
    FOREIGN KEY (`related_comment`)
    REFERENCES `mydb`.`comment` (`comment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
